version: "3.8"

x-application:

  readme: |
    httk development environment

  override-default: |
    version: "3.8"

    services:
      run:
         volumes:
           - "${HOME}/Documents/containers/devel:/home/${USER}/Documents/containers/devel"
         working_dir: "/home/${USER}/Documents/containers/devel"

      setup:
         volumes:
           - "${HOME}/Documents/containers/devel:/home/${USER}/Documents/containers/devel"
         working_dir: "/home/${USER}/Documents/containers/devel"

      setup-nonet:
         volumes:
           - "${HOME}/Documents/containers/devel:/home/${USER}/Documents/containers/devel"
         working_dir: "/home/${USER}/Documents/containers/devel"


  env-default: |
    # This container has no configurable options

  images:
    u24:
      pkgs:
        - default-jdk


x-launchers:
  download:
    service: setup
    type: setup

    # Zoom doesn't keep track of versions via filenames. TODO: implement handling of this so old versions are kept.
    script: &download_script
      - echo "DOWNLOAD"
      - export PATH="/home/${USER}/.local/bin:$${PATH}"
      - export DEV_DIR="$$(pwd -P)"
      - mkdir -p ~/.local/share/icons/hicolor/scalable
      - curl -L -o ~/.local/share/icons/hicolor/scalable/httk.svg https://httk.org/img/httk-logo-curves.svg
      - |
        if [ ! -e httk ]; then
          git clone 'https://github.com/httk/httk.git'
        fi
      - mkdir -p "uv/cache" "uv/home"
      - rm -rf ~/.local/share/uv
      - ln -s "$$(pwd -P)/uv/home" ~/.local/share/uv
      - export UV_CACHE_DIR="$$(pwd -P)/uv/cache"
      - pipx install --force uv
      - ln -nsf ../httk.venvs httk.venvs
      - mkdir -p ~/Downloads
      - cd ~/Downloads
      - echo "Download jmol"
      - FILENAME=$$(curl -sIL "https://sourceforge.net/projects/jmol/files/latest/download?source=files" | grep -o -E 'filename=.*$$' | sed -e 's/filename=//')
      - |
        if [ ! -e ~/Downloads/Jmol-latest-binary.zip -o \( -n "$$FILENAME" -a ! ~/Downloads/"$$FILENAME" \) ]; then
          curl -O -J -L --clobber "https://sourceforge.net/projects/jmol/files/latest/download?source=files"
          LATEST=$$(ls -t Jmol*.zip | head -1)
          ln -sf "$$LATEST" ~/Downloads/Jmol-latest-binary.zip
        fi
      - echo "Download isotropy"
      - FILENAME="iso.zip"
      - |
        if [ ! -e ~/Downloads/iso-latest.zip -o \( -n "$$FILENAME" -a ! ~/Downloads/"$$FILENAME" \) ]; then
          curl -o ~/Downloads/iso.zip --clobber -J -L "https://iso.byu.edu/iso/iso.zip"
          ln -sf iso.zip ~/Downloads/iso-latest.zip
        fi
      - echo "Download Miniforge"
      - LATESTURL="$$(curl -s https://api.github.com/repos/conda-forge/miniforge/releases/latest | jq --raw-output '.assets[] | .browser_download_url' | grep 'Miniforge3-.*-Linux-x86_64.sh$$')"
      - |
        if [ ! -e ~/Downloads/Miniforge3-latest-Linux-x86_64.sh -o ! -e ~/Downloads/"${LATESTURL##*/}" ]; then
          curl -L -O "$$LATESTURL"
          LATEST=$$(ls -t Miniforge3-*-Linux-x86_64.sh | head -1)
          ln -sf "$$LATEST" ~/Downloads/Miniforge3-latest-Linux-x86_64.sh
        fi
      - mkdir -p ~/.local/share
      - mkdir -p "httk.venvs/conda"
      - |
        if [ ! -e ~/.local/share/miniforge ]; then
          echo "Install miniforge (needed to complete the downloads)"
          bash ~/Downloads/Miniforge3-latest-Linux-x86_64.sh -b -s -p ~/.local/share/miniforge
        fi
      - source ~/.local/share/miniforge/etc/profile.d/conda.sh
      - conda config --add envs_dirs "$$DEV_DIR/conda/venvs"
      - conda config --add pkgs_dirs "$$DEV_DIR/conda/pkgs"
      - conda update -n base -c conda-forge conda -y
      - conda config --remove-key auto_activate_base 2>/dev/null || true
      - conda config --set auto_activate false
      - |
        conda config --set env_prompt '(conda: {name}) '

  redownload:
    service: setup
    type: setup
    script: &redownload_script
      - echo "REDOWNLOAD"
      - |
        if [ -e httk ]; then
          echo "httk develop directory already exist; will not remove possibly edited files automatically. Please remove or rename this directory manually if you want to replace it."
        fi
      - rm -f httk.venvs/bootstrap
      - rm -f "$$(readlink -f Downloads/Jmol-latest-binary.zip)"
      - rm -f Downloads/Jmol-latest-binary.zip
      - rm -f "$$(readlink -f Downloads/iso-latest.zip)"
      - rm -f Downloads/iso-latest.zip
      - *download_script

    #  - (conda activate py27 && virtualenv httk.venvs/py27 && source httk.venvs/py27/bin/activate && python -m pip install -r httk/requirements.txt)
    #  - (conda activate py310 && python -m venv httk.venvs/py310 && source httk.venvs/py310/bin/activate && python -m pip install -r httk/requirements.txt)

#      - uv venv --python 2.7 httk.venvs/py27
#      - (source httk.venvs/py27/bin/activate; uv pip install -r httk/requirements.txt)

#      - uv venv --python 3.10 httk.venvs/py310
#      - uv pip install --python httk.venvs/py39/bin/python -r httk/requirements.txt
#      - uv venv --python 3.12 httk.venvs/py312
#      - uv pip install --python httk.venvs/py312/bin/python -r httk/requirements.txt


  install:
    service: setup-nonet
    type: setup
    script: &install_script
      - echo "INSTALL";
      - export PATH="/home/${USER}/.local/bin:$${PATH}"
      - export UV_CACHE_DIR="$$(pwd -P)/uv/cache"
      - mkdir -p ~/.local/share
      - ln -nsf ../httk.venvs httk/.venvs
      - |
        if [ ! -e ~/.local/share/jmol ]; then
          mkdir ~/.local/share/jmol
          cd ~/.local/share/jmol
          unzip ~/Downloads/Jmol-latest-binary.zip
          LATEST=$$(ls -t | head -1)
          ln -sf "$$LATEST" latest
          chmod +x latest/jmol.sh
        fi
      - |
        if [ ! -e ~/.local/share/isotropy ]; then
          mkdir ~/.local/share/isotropy
          cd ~/.local/share/isotropy
          unzip ~/Downloads/iso-latest.zip
        fi

  reinstall:
    #service: setup-nonet
    service: setup
    type: setup
    script: &reinstall_script
      - echo "REINSTALL"
      - rm -rf ~/.local/share/jmol
      - rm -rf ~/.local/share/isotropy
      - rm -rf ~/.local/share/miniforge
      - *install_script

  update-check:
    service: setup
    type: setup
    script: &update_check_script
      - echo "UPDATE CHECK"
      - echo "Development environment: update manually with git pull"
      - exit 0

  update:
    service: setup
    type: setup
    script:
      - echo "UPDATE"
      - echo "Development environment: update manually with git pull"

  httk-console:
    service: run
    type: console
    script:
      - echo "httk-devel"
      - export DEV_DIR="$$(pwd -P)"
      - export HTTK_DIR="$$DEV_DIR/httk"
      - export PATH=~/.local/bin:~/.local/share/jmol/latest:~/.local/share/isotropy:"$$PATH"
      - export UV_CACHE_DIR="$$(pwd -P)/uv/cache"
      - export ISODATA=~/.local/share/isotropy/
      - export CONDA_PKGS_DIRS="$$(pwd -P)/conda/pkgs"
      - export CONDA_ENVS_PATH="$$(pwd -P)/httk/.venvs/conda"
      - cd httk
      - mkdir -p .venvs/
      - |
        if [ ! -e .venvs/system ]; then
          python3 -m venv .venvs/system
          source .venvs/system/bin/activate
          python3 -m pip install -r requirements.txt -r requirements-dev.txt
          python3 -m pip install -e .
        fi
      - if [ ! -e .venv ]; then ln -s .venvs/system .venv; fi
      - if [ ! -e .venvs/system/bin/activate ]; then echo "Your venv in venvs/system seems broken? Remove and run 'make venv' to recreate it."; fi
      - echo "===================================================================================================="
      - echo ""
      - echo "You should now be in a configured, working venv"
      - echo ""
      - echo "  httk-dev-console sets up a venv for the system python in .venvs/system, and symlinks .venv -> .venvs/system"
      - echo "  Then the venv pointed to by .venv is activated"
      - echo "  To create other venvs, use, e.g., 'make init_uv_venv venv=py312' or 'make init_conda_venv venv=py312'"
      - echo "  Activate them by, e.g., '.venvs/uv/py312/bin/activate' or 'conda activate py312'."
      - echo ""
      - echo "If the dependencies change, use:"
      - echo "   python -m pip install -r requirements.txt -r requirements-dev.tex."
      - echo ""
      - echo "===================================================================================================="
      - bash --init-file <(echo "source ~/.local/share/miniforge/etc/profile.d/conda.sh; source .venv/bin/activate; source init.shell")

    desktop:

      file: |
        [Desktop Entry]
        Name=httk console (container)
        Comment=httk console
        Exec=httk-console %U
        Terminal=true
        Type=Application
        Icon=httk
        Categories=Development;

      icons:
        - source: .local/share/icons/hicolor/scalable/httk.svg
          size: scalable
          dest: httk.svg

services:

  ## COMMON PART ##

  common: &common

    image: "cdc-u24"

    entrypoint: ["/cdc/entrypoint"]
    network_mode: none

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"
      NO_AT_BRIDGE: 1

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    devices:
      - "/dev/dri:/dev/dri"

    security_opt:
      - no-new-privileges

    userns_mode: "keep-id"


  setup:
    <<: *common

    network_mode: bridge

  setup-nonet:
    <<: *common

    network_mode: none

  run:
    <<: *common

    network_mode: bridge

    volumes:
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    x-features:
      - x11
