version: "3.8"

x-application:

  readme: |
    Flashprint: slicing software by Flashforge

    Flashprint does not presently seem to work under wayland (at least not with addition configuration); the 3D window doesn't render.
    (but can be started under wayland by setting: QT_QPA_PLATFORM: wayland )

  override-default: |
    version: "3.8"

    services:
      flashprint:
        volumes:
          - "${HOME}/Documents/containers/3d-projects:/home/${USER}/Documents/containers/3d-projects"
        working_dir: "/home/${USER}/Documents/containers/3d-projects"

  env-default: |
    # This container has no configurable options

services:

  ## COMMON PART ##

  common: &common

    image: "cdc-u24"

    working_dir: /home/${USER}
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "/tmp/${USER}/run"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_APP_DIR}/home:/home/${USER}:rw"

    devices:
      - "/dev/dri:/dev/dri"

    security_opt:
      - no-new-privileges

    userns_mode: "keep-id"

    network_node: none

  ## INSTALL ##

  download: &download
    <<: *common

    network_node: bridge

    command:
      - echo "DOWNLOAD"
      - mkdir -p Downloads
      - LATESTURL="$$(curl -L -N 'https://flashforge.com/blogs/download-software/software' | sed -n '\|^.*"\(https://[^/]\+/FlashPrint_[0-9.]\+/flashprint5_[0-9.]\+_amd64.deb\)".*$$|{s||\1|p;q}')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
        fi;
      - curl -L -o Downloads/$$LATESTFILENAME "$$LATESTURL" &&
        ln -sf $$LATESTFILENAME Downloads/flashprint5_latest_amd64.deb

  download-clean:
    <<: *common

    command:
      - echo "DOWNLOAD CLEAN"
      - rm -f "$$(readlink -f Downloads/flashprint5_latest_amd64.deb)"
      - rm -f Downloads/flashprint5_latest_amd64.deb


  install: &install
    <<: *common

    command:
      - VERSION="$${1:-flashprint5_latest_amd64.deb}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/.local/share/flashprint &&
        mkdir -p ~/.local/share/flashprint &&
        cd ~/.local/share/flashprint &&
        dpkg-deb -x ~/Downloads/"$$VERSION" flashprint &&
        mkdir -p ~/.local/share/applications &&
        cp flashprint/usr/share/applications/FlashPrint5.desktop ~/.local/share/applications/FlashPrint5.desktop &&
        sed -i 's%^Exec=/usr/share/FlashPrint5$$%Exec=/home/$${USER}/install/flashprint/usr/share/FlashPrint5/%' ~/.local/share/applications/FlashPrint5.desktop

  install-clean:
    <<: *common

    command:
      - rm -rf ~/.local/share/flashprint


  ## UPDATE ##

  update-check: &update-check
    <<: *common

    network_node: bridge

    command:
      - echo "UPDATE CHECK"
      - LATESTURL="$$(curl -L -N 'https://flashforge.com/blogs/download-software/software' | sed -n '\|^.*"\(https:[^/]\+/FlashPrint_[0-9.]\+/flashprint5_[0-9.]\+-amd64.deb\)".*$$|{s||\1|p;q}')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 0;
      - fi
      - mkdir -p Downloads
      - if [ -e "Downloads/$$LATESTFILENAME" ]; then
          echo "No new version";
          exit 0;
        fi
      - echo "File missing, or server-side file newer"
      - exit 1

  update: &update
    <<: *install


  ## EXECUTE ###

  flashprint:
    <<: *common

    container_name: cdc_flashprint_flashprint

    network_node: bridge

    x-app-features:
      - x11

    command:
      - echo "FLASHPRINT"
      - LD_LIBRARY_PATH=~/.local/share/flashprint/flashprint/usr/lib exec ~/.local/share/flashprint/flashprint/usr/share/FlashPrint5/FlashPrint "$$@"

    x-launcher:
      desktop:
        file: |
          [Desktop Entry]
          GenericName=FlashPrint5
          Name=FlashForge 3D Printer Control Software v5 (container)
          StartupWMClass=FlashPrint
          MimeType=text/plain;
          Exec=flashprint
          Icon=flashforge5
          Type=Application
          Terminal=false
          Categories=Utility;

        icons:
          - source: flashforge5.png
            dest: flashforge5.png

  flashprint-wayland:
    <<: *common

    container_name: cdc_flashprint_flashprint

    network_node: bridge

    x-app-features:
      - wayland

    command:
      - echo "FLASHPRINT-WAYLAND -- WARNING, this currently does not seem to work"
      - QT_QPA_PLATFORM=wayland LD_LIBRARY_PATH=~/.local/share/flashprint/flashprint/usr/lib exec ~/.local/share/flashprint/flashprint/usr/share/FlashPrint5/FlashPrint "$$@"

    x-launcher:
        desktop:


  ## INTERACTIVE ##

  interactive:
    <<: *common

    command:
      - echo "INTERACTIVE"
      - bash "$$@"
