version: "3.8"

x-application:

  name: Obsidian

  label: obsidian

  readme: |
    Obsidian: personal knowledge base and note-taking software application.

  config-default: |
    version: "3.8"

    services:
      run:
         volumes:
           - "${HOME}/Documents/containers/notes:/home/${USER}/Documents/containers/notes"
         working_dir: "/home/${USER}/Documents/containers/notes"

  images:
    u24:
      pkgs:
        - texlive-latex-base
        - texlive-latex-extra
        - texlive-luatex


x-launchers:
  download:
    service: setup
    type: setup

    script: &download_script
      - echo "DOWNLOAD"
      - mkdir -p Downloads
      - LATESTURL="$$(curl -L 'https://obsidian.md/download' | sed -n 's|^.*"\(https://.*/obsidian_[0-9.]\+_amd64\.deb\)".*$$|\1|p')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
        fi
      - echo curl -L -o "Downloads/$$LATESTFILENAME" "$$LATESTURL" && ln -sf $$LATESTFILENAME Downloads/obsidian_latest_amd64.deb
      - curl -L -o "Downloads/$$LATESTFILENAME" "$$LATESTURL" && ln -sf $$LATESTFILENAME Downloads/obsidian_latest_amd64.deb

  redownload:
    service: setup
    type: setup
    script: &redownload_script
      - echo "REDOWNLOAD"
      - rm -f "$$(readlink -f Downloads/obsidian_latest_amd64.deb)"
      - rm -f Downloads/obsidian_latest_amd64.deb
      - *download_script

  install:
    service: setup-nonet
    type: setup
    script: &install_script
      - VERSION="$${1:-obsidian_latest_amd64.deb}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/.local/share/obsidian &&
        mkdir ~/.local/share/obsidian &&
        cd ~/.local/share/obsidian &&
        dpkg-deb -x ~/Downloads/"$$VERSION" obsidian &&
        mkdir -p ~/.local/share/applications ~/.local/share/icons/hicolor/256x256/apps/ &&
        cp obsidian/usr/share/applications/obsidian.desktop ~/.local/share/applications/obsidian.desktop &&
        sed -i 's%^Exec=.*%Exec=/home/${USER}/obsidian/obsidian/opt/Obsidian/%' ~/.local/share/applications/obsidian.desktop ~/.local/share/applications/obsidian.desktop &&
        cp obsidian/usr/share/icons/hicolor/256x256/apps/obsidian.png ~/.local/share/icons/hicolor/256x256/apps/.

  reinstall:
    service: setup-nonet
    type: setup
    script: &reinstall_script
      - echo "REINSTALL"
      - rm -rf ~/.local/share/obsidian
      - *install_script

  update-check:
    service: setup
    type: setup
    script: &update_check_script
      - echo "UPDATE CHECK"
      - mkdir -p Downloads
      - LATESTURL="$$(curl -L 'https://obsidian.md/download' | sed -n 's|^.*"\(https://.*/obsidian_[0-9.]\+_amd64\.deb\)".*$$|\1|p')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -e "Downloads/$$LATESTFILENAME" ]; then
          echo "No new version";
          exit 0;
        fi;
      - echo "File missing, or server-side file newer"
      - exit 1

  update:
    service: setup
    type: setup
    script:
      - echo "UPDATE"
      - *download_script
      - *reinstall_script

  obsidian:
    service: run
    type: background
    script:
      - echo "OBSIDIAN";
      - LD_LIBRARY_PATH=~/.local/share/obsidian/obsidian/opt/Obsidian exec ~/.local/share/obsidian/obsidian/opt/Obsidian/obsidian $${CDC_OZONE_FLAGS} "$$@"

    desktop:

      file: |
        [Desktop Entry]
        Name=Obsidian (container)
        StartupWMClass=obsidian
        Comment=Personal knowledge base and note-taking software application.
        Exec=obsidian %U
        Terminal=false
        Type=Application
        Icon=obsidian
        Categories=Utility;

      icons:
        - source: obsidian.png
          dest: obsidian.png

services:

  common: &common

    image: "cdc-u24"

    entrypoint: ["/bin/tini", "/bin/bash", "--", "-c", "$$(printf \"%s\\n\" \"$@\"); sleep infinity"]
    network_mode: none

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "/tmp/${USER}/run"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"
      DESKTOP_SESSION: "${DESKTOP_SESSION}"

    cap_drop:
      - ALL

    cap_add:
      - SYS_CHROOT

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes:
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    devices:
      - "/dev/dri:/dev/dri"

    security_opt:
      - no-new-privileges

    userns_mode: "keep-id"

  setup:
    <<: *common

    network_mode: bridge

  setup-nonet:
    <<: *common

    network_mode: none

  run:
    <<: *common

    network_mode: bridge

    volumes:
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"
      - "${CDC_APP_PATH}/home/.local/share/zoom/zoom:/opt/zoom:ro"

    x-features:
      - dri
      - wayland-fallback-x11
