version: "3.8"

x-application:

  readme: |
    Obsidian: personal knowledge base and note-taking software application.

  config-default: |
    version: "3.8"

    # This container has no configurable options

  images:
    u24:
      pkgs:
        - texlive-latex-base
        - texlive-latex-extra

services:

  ## COMMON PART ##

  common: &common

    image: "cdc-u24"

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "/tmp/${USER}/run"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"

    cap_drop:
      - ALL
    cap_add:
      - SYS_CHROOT

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_APP_DIR}/home:/home/${USER}:rw"

    devices:
      - "/dev/dri:/dev/dri"

    security_opt:
      - no-new-privileges

    userns_mode: "keep-id"

    network_mode: none


  ## INSTALL ##

  download: &download
    <<: *common

    network_mode: bridge

    environment:
      <<: *common-env

    command:
      - echo "DOWNLOAD"
      - mkdir -p Downloads
      - LATESTURL="$$(curl -L 'https://obsidian.md/download' | sed -n 's|^.*"\(https://.*/obsidian_[0-9.]\+_amd64\.deb\)".*$$|\1|p')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
        fi
      - echo curl -L -o "Downloads/$$LATESTFILENAME" "$$LATESTURL" && ln -sf $$LATESTFILENAME Downloads/obsidian_latest_amd64.deb
      - curl -L -o "Downloads/$$LATESTFILENAME" "$$LATESTURL" && ln -sf $$LATESTFILENAME Downloads/obsidian_latest_amd64.deb

  install: &install
    <<: *common

    command:
      - VERSION="$${1:-obsidian_latest_amd64.deb}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/Installation &&
        mkdir ~/Installation &&
        cd ~/Installation &&
        dpkg-deb -x ~/Downloads/"$$VERSION" obsidian &&
        mkdir -p ~/.local/share/applications ~/.local/share/icons/hicolor/256x256/apps/ &&
        cp obsidian/usr/share/applications/obsidian.desktop ~/.local/share/applications/obsidian.desktop &&
        sed -i 's%^Exec=.*%Exec=/home/${USER}/obsidian/obsidian/opt/Obsidian/%' ~/.local/share/applications/obsidian.desktop ~/.local/share/applications/obsidian.desktop &&
        cp obsidian/usr/share/icons/hicolor/256x256/apps/obsidian.png ~/.local/share/icons/hicolor/256x256/apps/.


  ## UPDATE ##

  update-check: &update-check
    <<: *common

    network_mode: bridge

    command:
      - echo "UPDATE CHECK"
      - mkdir -p Downloads
      - LATESTURL="$$(curl -L 'https://obsidian.md/download' | sed -n 's|^.*"\(https://.*/obsidian_[0-9.]\+_amd64\.deb\)".*$$|\1|p')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -e "Downloads/$$LATESTFILENAME" ]; then
          echo "No new version";
          exit 0;
        fi;
      - echo "File missing, or server-side file newer"
      - exit 1

  update: &update
    <<: *install


  ## EXECUTE ###

  obsidian:
    <<: *common

    container_name: cdc_obsidian_obsidian

    network_mode: bridge

    x-app-features:
      - wayland-fallback-x11

    command:
      - echo "OBSIDIAN";
      - if [ -n "$WAYLAND_DISPLAY" ]; then
           LD_LIBRARY_PATH=~/Installation/obsidian/opt/Obsidian exec Installation/obsidian/opt/Obsidian/obsidian --ozone-platform=wayland --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations "$$@"
        else
           LD_LIBRARY_PATH=~/Installation/obsidian/opt/Obsidian exec Installation/obsidian/opt/Obsidian/obsidian "$$@"
        fi

    x-launcher:

      desktop:

        file: |
          [Desktop Entry]
          Name=Obsidian (container)
          StartupWMClass=obsidian
          Comment=Personal knowledge base and note-taking software application.
          Exec=obsidian %U
          Terminal=false
          Type=Application
          Icon=obsidian
          Categories=Utility;

        icons:
          - source: obsidian.png
            dest: obsidian.png

  ## INTERACTIVE ##

  interactive:
    <<: *common

    x-app-features:
      - wayland-fallback-x11

    command:
      - echo "INTERACTIVE"
      - bash
