version: "3.8"

x-application:

  readme: |
    Obsidian: personal knowledge base and note-taking software application.

  config-default: |
    version: "3.8"

    # This container has no configurable options

  image:
    ubuntu-22.04:
      packages:
        - texlive-latex-base
        - texlive-latex-extra

services:

  ## COMMON PART ##

  common: &common

    image: "desktop-container-default"

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
      XDG_CURRENT_DESKTOP: "GNOME"
      BROWSER: "falkon"
      DISPLAY: "${DISPLAY}"
      XAUTHORITY: "${XAUTHORITY}"
      
      #DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/${USER}/run/bus"

    cap_drop:
      - ALL
    cap_add:
      - SYS_CHROOT

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_HOME}/home:/home/${USER}:rw"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY}:${XAUTHORITY}:rw"
      - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"
      - "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${USER}/run/${WAYLAND_DISPLAY}:ro"
      
    # - "${CDC_DBUS_PATH}:/tmp/${USER}/run/bus:rw"

    devices:
      - "/dev/dri:/dev/dri"

    security_opt:
      - "label=no-new-privileges"

    userns_mode: "keep-id"


  ## INSTALL ##
  
  download: &download
    <<: *common

    environment:
      <<: *common-env

    command:
      - echo "DOWNLOAD"
      - mkdir -p Downloads
      - LATESTURL="$$(curl -L 'https://obsidian.md/download' | sed -n 's|^.*"\(https://.*/obsidian_[0-9.]\+_amd64\.deb\)".*$$|\1|p')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
        fi
      - echo curl -L -o "Downloads/$$LATESTFILENAME" "$$LATESTURL" && ln -sf $$LATESTFILENAME Downloads/obsidian_latest_amd64.deb
      - curl -L -o "Downloads/$$LATESTFILENAME" "$$LATESTURL" && ln -sf $$LATESTFILENAME Downloads/obsidian_latest_amd64.deb

  install: &install
    <<: *common 

    command:
      - VERSION="$${1-obsidian_latest_amd64.deb}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/Installation &&
        mkdir ~/Installation &&
        cd ~/Installation &&
        dpkg-deb -x ~/Downloads/"$$VERSION" obsidian &&
        mkdir -p ~/.local/share/applications ~/.local/share/icons/hicolor/256x256/apps/ &&
        cp obsidian/usr/share/applications/obsidian.desktop ~/.local/share/applications/obsidian.desktop &&
        sed -i 's%^Exec=.*%Exec=/home/${USER}/obsidian/obsidian/opt/Obsidian/%' ~/.local/share/applications/obsidian.desktop ~/.local/share/applications/obsidian.desktop &&
        cp obsidian/usr/share/icons/hicolor/256x256/apps/obsidian.png ~/.local/share/icons/hicolor/256x256/apps/.


  ## UPDATE ##

  update-check: &update-check
    <<: *common 

    command:
      - echo "UPDATE CHECK"
      - mkdir -p Downloads
      - LATESTURL="$$(curl -L 'https://obsidian.md/download' | sed -n 's|^.*"\(https://.*/obsidian_[0-9.]\+_amd64\.deb\)".*$$|\1|p')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -e "Downloads/$$LATESTFILENAME" ]; then
          echo "No new version";
          exit 0;
        fi;
      - echo "File missing, or server-side file newer"
      - exit 1 

  update: &update
    <<: *install 


  ## EXECUTE ###

  obsidian:
    <<: *common

    container_name: cdc_obsidian_obsidian

    command:
      - echo "OBSIDIAN";
      - xdg-settings set default-web-browser org.kde.falkon.desktop;
      - LD_LIBRARY_PATH=~/Installation/obsidian/opt/Obsidian exec Installation/obsidian/opt/Obsidian/obsidian "$$@"

    x-launcher:
    
      desktop:

        file: |
          [Desktop Entry]
          Name=Obsidian (container)
          StartupWMClass=obsidian
          Comment=Personal knowledge base and note-taking software application.
          Exec=obsidian %U
          Terminal=false
          Type=Application
          Icon=obsidian
          Categories=Utility;
          
        icons:
          - source: Installation/obsidian/usr/share/icons/hicolor/256x256/apps/obsidian.png
            size: 256
            dest: obsidian.png

  ## INTERACTIVE ##

  interactive:
    <<: *common

    image: "desktop-container-default"

    command:
      - echo "INTERACTIVE"
      - bash
