version: "3.8"

x-application:

  readme: |
    Spotify-client: client for the audio streaming and media service provider Spotify

  override-default: |
    version: "3.8"

    # Comment out as desired below to give spotify access to dbus session and/or system bus
    #
    #services:
    #  spotify:
    #    volumes:
    #      - "${CDC_DBUS_PATH}:/tmp/${USER}/run/bus:rw"
    #      - "${CDC_DBUS_SYSTEM_BUS_PATH}:/run/dbus/system_bus_socket:rw"
    #    environment:
    #      DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/${USER}/run/bus"
    #      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"
    #    x-launcher:
    #      dbus-proxy: --filter
    #      dbus-system-proxy: --filter
    #

  env-default: |
    # No configurable options


services:

  ## COMMON PART ##

  common: &common

    image: "desktop-container-default"

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"
      BROWSER: "falkon"
      DISPLAY: "${DISPLAY}"
      XAUTHORITY: "${XAUTHORITY}"
      DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/${USER}/run/bus"

    cap_drop:
      - ALL
    cap_add:
      - SYS_CHROOT

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_APP_DIR}/home:/home/${USER}:rw"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY}:${XAUTHORITY}:rw"
      - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"
      - "${CDC_DBUS_PATH}:/tmp/${USER}/run/bus:rw"

    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/snd:/dev/snd"

    security_opt:
      - "label=disable"

    userns_mode: "keep-id"


  ## INSTALL ##

  download: &download
    <<: *common

    command:
      - echo "DOWNLOAD"
      - mkdir -p Downloads
      - LATESTURL="http://repository.spotify.com/pool/non-free/s/spotify-client/$(curl -L 'http://repository.spotify.com/pool/non-free/s/spotify-client/' | sed -n 's|^.*"\(spotify-client_.\+_amd64\.deb\)".*$|\1|p' | sort --version-sort | tail -n 1)"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
        fi;
      - curl -L -o Downloads/$$LATESTFILENAME "$$LATESTURL" && ln -sf $$LATESTFILENAME Downloads/spotify-client_latest_amd64.deb

  install: &install
    <<: *common

    # Note: the spotify install MUST be under ~/.local/share/spotify for the handling of icons to work
    # because sometimes icon file names are sent from container to host
    command:
      - VERSION="$${1-spotify-client_latest_amd64.deb}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/Installation 
      - rm -rf ~/.local/share/spotify
      - mkdir ~/Installation &&
        cd ~/Installation &&
        dpkg-deb -x ~/Downloads/"$$VERSION" spotify &&
        mv spotify/usr/share/spotify ~/.local/share/spotify &&
        mkdir -p ~/.local/share/applications ~/.local/share/icons/hicolor/256x256/apps &&
        cp ~/.local/share/spotify/spotify.desktop ~/.local/share/applications/spotify.desktop &&
        sed -i 's%/usr/bin/spotify%/home/${USER}/Installation/spotify/usr/bin/spotify%' ~/.local/share/applications/spotify.desktop &&
        for ICON in ~/.local/share/spotify/icons/spotify-linux-*.png; do
          SIZE=$${ICON#spotify/usr/share/spotify/icons/spotify-linux-};
          SIZE=$${SIZE%.png};
          mkdir -p ~/.local/share/icons/hicolor/"$${SIZE}x$${SIZE}"/apps;
          cp $$ICON ~/.local/share/icons/hicolor/"$${SIZE}x$${SIZE}"/apps;
        done &&
        cp ~/.local/share/spotify/icons/spotify-linux-256.png ~/.local/share/icons/hicolor/256x256/apps/spotify-client.png &&
        cp ~/.local/share/spotify/icons/spotify-linux-256.png ~/.local/share/icons/hicolor/256x256/apps/spotify.png &&
        gtk-update-icon-cache -f -t ~/.local/share/icons/hicolor &&
        update-desktop-database ~/.local/share/applications/ &&
        rm -rf ~/Installation

  ## UPDATE ##

  update-check: &update-check
    <<: *common

    command:
      - echo "UPDATE CHECK"
      - LATESTURL="http://repository.spotify.com/pool/non-free/s/spotify-client/$(curl -L 'http://repository.spotify.com/pool/non-free/s/spotify-client/' | sed -n 's|^.*"\(spotify-client_.\+_amd64\.deb\)".*$|\1|p')"
      - LATESTFILENAME="$${LATESTURL##*/}";
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
      - fi
      - mkdir -p Downloads
      - if [ -e "Downloads/$$LATESTFILENAME" ]; then
          echo "No new version";
          exit 0;
        fi
      - echo "File missing, or server-side file newer"
      - exit 1

  update: &update
    <<: *install


  ## EXECUTE ###

  spotify:
    <<: *common

    container_name: cdc_spotify_spotify

    command:
      - echo "SPOTIFY"
      - pipewire-pulse &
      - exec ~/.local/share/spotify/spotify "$$@"

    x-launcher:

      dbus-proxy: --filter --own=org.mpris.MediaPlayer2.spotify --call="org.freedesktop.portal.*=*" --talk=org.gnome.SettingsDaemon.MediaKeys --talk=org.kde.StatusNotifierWatcher

      devices:
        - video

      desktop:

        file: |
          [Desktop Entry]
          Type=Application
          Name=Spotify (container)
          StartupWMClass=spotify
          GenericName=Music Player
          Icon=spotify-linux-256
          Exec=spotify %U
          Terminal=false
          MimeType=x-scheme-handler/spotify;
          Categories=Audio;Music;Player;AudioVideo;

        icons:
          - source: .local/share/icons/hicolor/256x256/apps/spotify-linux-256.png
            size: 256
            dest: spotify-linux-256.png
          - source: .local/share/icons/hicolor/256x256/apps/spotify-linux-256.png
            size: 256
            dest: spotify-client.png
          - source: .local/share/icons/hicolor/256x256/apps/spotify-linux-256.png
            size: 256
            dest: spotify.png
          - source: .local/share/icons/hicolor/512x512/apps/spotify-linux-512.png
            size: 512
            dest: spotify-linux-512.png     
          - source: .local/share/icons/hicolor/128x128/apps/spotify-linux-128.png
            size: 128
            dest: spotify-linux-128.png
          - source: .local/share/icons/hicolor/16x16/apps/spotify-linux-16.png
            size: 16
            dest: spotify-linux-16.png
          - source: .local/share/icons/hicolor/22x22/apps/spotify-linux-22.png
            size: 22
            dest: spotify-linux-22.png
          - source: .local/share/icons/hicolor/24x24/apps/spotify-linux-24.png
            size: 24
            dest: spotify-linux-24.png
          - source: .local/share/icons/hicolor/32x32/apps/spotify-linux-32.png
            size: 32
            dest: spotify-linux-32.png
          - source: .local/share/icons/hicolor/48x48/apps/spotify-linux-48.png
            size: 48
            dest: spotify-linux-48.png
          - source: .local/share/icons/hicolor/64x64/apps/spotify-linux-64.png
            size: 64
            dest: spotify-linux-64.png      
          - source: .local/share/icons/hicolor/512x512/apps/spotify-linux-512.png
            size: 512
            dest: spotify-linux-512.png
          - source: .local/share/icons/hicolor/32x32/apps/spotify-linux-32.png
            dest: icons/spotify-linux-32.png
          - source: .local/share/icons/hicolor/256x256/apps/spotify-linux-256.png
            dest: icons/spotify-linux-256.png
          - source: .local/share/icons/hicolor/64x64/apps/spotify-linux-64.png
            dest: icons/spotify-linux-64.png        


  ## INTERACTIVE ##

  interactive:
    <<: *common

    command:
      - echo "INTERACTIVE"
      - bash
