version: "3.8"

x-application:

  readme: |
    Flashprint: slicing software by Flashforge

    Flashprint does not presently seem to work under wayland (at least not with addition configuration); the 3D window doesn't render.
    (but can be started under wayland by setting: QT_QPA_PLATFORM: wayland )

  override-default: |
    version: "3.8"

    services:
      flashprint:
        volumes:
          - "${HOME}/Documents/containers/3d-projects:/home/${USER}/Documents/containers/3d-projects"
        working_dir: "/home/${USER}/Documents/containers/3d-projects"

  env-default: |
    # This container has no configurable options

  images:
    u24:
      pkgs: ["libudev-dev", "libqt5gui5", "libqt5core5a", "libqt5opengl5", "libqt5network5", "libqt5xml5", "libftdi-dev", "libftdi1-dev", "libhidapi-dev", "libelf1", "libusb-0.1-4"]

x-launchers:
  download:
    service: setup
    type: setup
    script: &download_script
      - echo "DOWNLOAD"
      - mkdir -p Downloads
      - LATESTURL="$$(curl -L -N 'https://flashforge.com/blogs/download-software/software' | sed -n '\|^.*"\(https://[^/]\+/FlashPrint_[0-9.]\+/flashprint5_[0-9.]\+_amd64.deb\)".*$$|{s||\1|p;q}')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
        fi;
      - curl -L -o Downloads/$$LATESTFILENAME "$$LATESTURL" &&
        ln -sf $$LATESTFILENAME Downloads/flashprint5_latest_amd64.deb

  redownload:
    service: setup
    type: setup
    script: &redownload_script
      - echo "REDOWNLOAD"
      - rm -f "$$(readlink -f Downloads/flashprint5_latest_amd64.deb)"
      - rm -f Downloads/flashprint5_latest_amd64.deb
      - *download_script

  install:
    service: setup-nonet
    type: setup
    script: &install_script
      - VERSION="$${1:-flashprint5_latest_amd64.deb}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/.local/share/flashprint &&
        mkdir -p ~/.local/share/flashprint &&
        cd ~/.local/share/flashprint &&
        dpkg-deb -x ~/Downloads/"$$VERSION" flashprint &&
        mkdir -p ~/.local/share/applications &&
        cp flashprint/usr/share/applications/FlashPrint5.desktop ~/.local/share/applications/FlashPrint5.desktop &&
        sed -i 's%^Exec=/usr/share/FlashPrint5$$%Exec=/home/$${USER}/install/flashprint/usr/share/FlashPrint5/%' ~/.local/share/applications/FlashPrint5.desktop

  reinstall:
    service: setup-nonet
    type: setup
    script: &reinstall_script
      - VERSION="$${1:-flashprint5_latest_amd64.deb}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/.local/share/flashprint
      - *install_script

  update-check:
    service: setup
    type: setup
    script:
      - echo "UPDATE CHECK"
      - LATESTURL="$$(curl -L -N 'https://flashforge.com/blogs/download-software/software' | sed -n '\|^.*"\(https:[^/]\+/FlashPrint_[0-9.]\+/flashprint5_[0-9.]\+-amd64.deb\)".*$$|{s||\1|p;q}')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 0;
      - fi
      - mkdir -p Downloads
      - if [ -e "Downloads/$$LATESTFILENAME" ]; then
          echo "No new version";
          exit 0;
        fi
      - echo "File missing, or server-side file newer"
      - exit 1

  update:
    service: setup
    type: setup
    script:
      - echo "UPDATE"
      - *redownload_script
      - *reinstall_script

  flashprint:
    service: run
    type: background
    script:
      - echo "FLASHPRINT"
      - LD_LIBRARY_PATH=~/.local/share/flashprint/flashprint/usr/lib exec ~/.local/share/flashprint/flashprint/usr/share/FlashPrint5/FlashPrint "$$@"

    desktop:
      file: |
        [Desktop Entry]
        GenericName=FlashPrint5
        Name=FlashForge 3D Printer Control Software v5 (container)
        StartupWMClass=FlashPrint
        MimeType=text/plain;
        Exec=flashprint
        Icon=flashforge5
        Type=Application
        Terminal=false
        Categories=Utility;

      icons:
        - source: flashforge5.png
          dest: flashforge5.png


  flashprint-wayland:
    service: run-wayland
    type: background
    script:
      - echo "FLASHPRINT"
      - LD_LIBRARY_PATH=~/.local/share/flashprint/flashprint/usr/lib exec ~/.local/share/flashprint/flashprint/usr/share/FlashPrint5/FlashPrint "$$@"

  interactive:
    service: run
    console: true
    script:
      - echo "INTERACTIVE"
      - bash

services:

  ## COMMON PART ##

  common: &common

    image: "cdc-u24"

    entrypoint: ["/cdc/entrypoint"]

    network: none

    working_dir: /home/${USER}
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "/tmp/${USER}/run"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"
      DESKTOP_SESSION: "${DESKTOP_SESSION}"

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    devices:
      - "/dev/dri:/dev/dri"

    security_opt:
      - no-new-privileges

    userns_mode: "keep-id"

    network_node: none


  setup:
    <<: *common

    network_mode: bridge

  setup-nonet:
    <<: *common

    network_mode: none

  run:
    <<: *common

    network_node: bridge
    read_only: false

    x-features:
      - x11

  run-wayland:
    <<: *common

    network_node: bridge
    read_only: false

    x-features:
      - wayland
