version: "3.8"

x-desktop-containers:
  readme: |
    Zoom: videotelephony software program.

    This container uses the x11 server on your desktop (i.e., likely xwayland if you are
    running Wayland), which is not great from a security barrier perspective. Zoom has support
    to run directly under wayland, but in present versions this support seem to cause issues
    (crashes, incomplete user interface, etc.), which is probably why current versions of Zoom
    at the time of writing this defaults to x11 even if Wayland is available.

  config-default: |
    version: "3.8"
    
    # This container has no configurable options

  dbus: filter
  devices:
    video:
      - exec
  desktop:
    zoom:
      file: |
        [Desktop Entry]
        Name=Zoom (container)
        StartupWMClass=zoom
        Comment=Zoom Video Conference
        Exec=ZoomLauncher %U
        Terminal=false
        Type=Application
        Encoding=UTF-8
        Icon=zoom
        Categories=Network;Application;
        MimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;
        X-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall
      icons:
        - source: files/extract/usr/share/pixmaps/Zoom.png
          dest: hicolor/256x256/apps/zoom.png

x-common: &common

  working_dir: /home/$USER
  hostname: "zoom_container"
  user: "${USER}"

  environment: &common-env
    LANG: "${LANG}"
    XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
    XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
    XDG_CURRENT_DESKTOP: "GNOME"
    BROWSER: "falkon"
    TERM: "xterm"
    XTERM_LOCALE: "en_US.UTF-8"
    XTERM_SHELL: "/usr/bin/bash"
    DISPLAY: "${DISPLAY}"
    XAUTHORITY: "${XAUTHORITY}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/${USER}/run/bus"
  
  cap_drop:
    - ALL
  cap_add:
    - SYS_CHROOT

  security_opt:
    - no-new-privileges
    
  read_only: true
  tmpfs:
    - /tmp
    - /run

  shm_size: "512m"

  volumes: &common-volumes
    - "./home:/home/${USER}:rw"
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:${XAUTHORITY}:rw"
    - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"
    - "${XDG_RUNTIME_DIR}/bus:/tmp/${USER}/run/bus:rw"
    
  devices:
    - "/dev/dri:/dev/dri"
    - "/dev/snd:/dev/snd"
    
  security_opt:
    - "label=disable"

  userns_mode: "keep-id"

services:

  install:
    <<: *common 

    container_name: zoom_container_runtime_install
    image: "desktop-container-default"

    environment:
      <<: *common-env
      LAUNCH_COMMAND: mkdir -p files; EXISTFLAG=""; if [ -e files/zoom_x86_64.tar.xz ]; then EXISTFLAG="-z files/zoom_x86_64.tar.xz"; fi; curl -L -o files/zoom_x86_64.tar.xz $EXISTFLAG "https://zoom.us/client/latest/zoom_x86_64.tar.xz" && rm -rf ~/zoom && mkdir ~/zoom && cd ~/zoom && tar -xvf ~/files/zoom_x86_64.tar.xz && mkdir -p ~/.local/share/applications && echo -e '[Desktop Entry]\nName=ZoomLauncher\nComment=Zoom Video Conference\nExec=/home/${USER}/zoom/zoom/ZoomLauncher %U\nTerminal=false\nType=Application\nEncoding=UTF-8\nCategories=Network;Application;\nMimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;\nX-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall\nName[en_US]=ZoomLauncher' > ~/.local/share/applications/ZoomLauncher.desktop && update-desktop-database ~/.local/share/applications/

  exec:
    <<: *common

    container_name: zoom_container_runtime
    image: "desktop-container-default"

    environment:
      <<: *common-env
      LAUNCH_COMMAND: "cd zoom/zoom; pipewire-pulse & LD_LIBRARY_PATH=/home/rar/zoom/zoom:/home/rar/zoom/zoom/Qt/lib exec ./zoom"

