version: "3.8"

x-application:

  readme: |
    httk development environment

  override-default: |
    version: "3.8"

    services:
      run:
         volumes:
           - "${HOME}/Documents/containers/devel:/home/${USER}/Documents/containers/devel"
         working_dir: "/home/${USER}/Documents/containers/devel"

      setup:
         volumes:
           - "${HOME}/Documents/containers/devel:/home/${USER}/Documents/containers/devel"
         working_dir: "/home/${USER}/Documents/containers/devel"

      setup-nonet:
         volumes:
           - "${HOME}/Documents/containers/devel:/home/${USER}/Documents/containers/devel"
         working_dir: "/home/${USER}/Documents/containers/devel"


  env-default: |
    # This container has no configurable options


x-launchers:
  download:
    service: setup
    type: setup

    # Zoom doesn't keep track of versions via filenames. TODO: implement handling of this so old versions are kept.
    script: &download_script
      - echo "DOWNLOAD"
      - mkdir -p ~/.local/share/icons/hicolor/scalable
      - curl -L -o ~/.local/share/icons/hicolor/scalable/httk.svg https://httk.org/img/httk-logo-curves.svg
      - |
        if [ ! -e httk ]; then
          git clone 'https://github.com/httk/httk.git'
        fi
      - DEVDIR=$$(pwd -P)
      - cd ~/Downloads
      - echo "Download Miniforge"
      - LATESTURL="$$(curl -s https://api.github.com/repos/conda-forge/miniforge/releases/latest | jq --raw-output '.assets[] | .browser_download_url' | grep 'Miniforge3-.*-Linux-x86_64.sh$$')"
      - |
        if [ ! -e ~/Downloads/Miniforge3-latest-Linux-x86_64.sh -o ! -e ~/Downloads/"${LATESTURL##*/}" ]; then
          curl -L -O "$$LATESTURL"
          LATEST=$$(ls -t Miniforge3-*-Linux-x86_64.sh | head -1)
          ln -sf "$$LATEST" ~/Downloads/Miniforge3-latest-Linux-x86_64.sh
        fi
      - mkdir -p ~/.local/share
      - |
        if [ ! -e ~/.local/share/miniforge ]; then
          echo "Install miniforge (needed to complete downloads)"
          bash ~/Downloads/Miniforge3-latest-Linux-x86_64.sh -b -s -p ~/.local/share/miniforge
          source ~/.local/share/miniforge/etc/profile.d/conda.sh
          conda config --add envs_dirs "$$DEVDIR/conda/envs"
          conda config --add pkgs_dirs "$$DEVDIR/conda/pkgs"
          conda config --set auto_activate_base false
        else
          source ~/.local/share/miniforge/etc/profile.d/conda.sh
        fi
      - mkdir -p "$$DEVDIR/conda"
      - mkdir -p "$$DEVDIR/httk-venvs/wheelhouse"
      - conda update -n base -c conda-forge conda -y
      - export CONDA_PKGS_DIRS="$$DEVDIR/conda/pkgs"
      - export CONDA_ENVS_PATH="$$DEVDIR/conda/envs"
      - conda list --name py39 > /dev/null || conda create -n py39 -c conda-forge python=3.9 -y
      - (conda activate py39 && python -m venv httk-venvs/py39 && source httk-venvs/py39/bin/activate && python -m pip download -r "$$DEVDIR/httk/requirements.txt" --check-build-dependencies --dest "$$DEVDIR/httk-venvs/wheelhouse")
      - conda list --name py27 > /dev/null || conda create -n py27 -c conda-forge python=2.7 virtualenv -y
      - (conda activate py27 && virtualenv httk-venvs/py27 && source httk-venvs/py27/bin/activate && python -m pip download -r "$$DEVDIR/httk/requirements.txt" --dest "$$DEVDIR/httk-venvs/wheelhouse")
      - echo "Download jmol"
      - FILENAME=$$(curl -sIL "https://sourceforge.net/projects/jmol/files/latest/download?source=files" | grep -o -E 'filename=.*$$' | sed -e 's/filename=//')
      - |
        if [ ! -e ~/Downloads/Jmol-latest-binary.zip -o \( -n "$$FILENAME" -a ! ~/Downloads/"$$FILENAME" \) ]; then
          curl -O -J -L --clobber "https://sourceforge.net/projects/jmol/files/latest/download?source=files"
          LATEST=$$(ls -t Jmol*.zip | head -1)
          ln -sf "$$LATEST" ~/Downloads/Jmol-latest-binary.zip
        fi
      - echo "Download isotropy"
      - FILENAME="iso.zip"
      - |
        if [ ! -e ~/Downloads/iso-latest.zip -o \( -n "$$FILENAME" -a ! ~/Downloads/"$$FILENAME" \) ]; then
          curl -o ~/Downloads/iso.zip --clobber -J -L "https://iso.byu.edu/iso/iso.zip"
          ln -sf iso.zip ~/Downloads/iso-latest.zip
        fi

  redownload:
    service: setup
    type: setup
    script: &redownload_script
      - echo "REDOWNLOAD"
      - |
        if [ -e httk ]; then
          echo "httk develop directory already exist; will not remove possibly edited files automatically. Please remove or rename this directory manually."
          exit 1
        fi
      - rm -f ~/.local/share/miniforge
      - rm -f "$$(readlink -f Downloads/Miniforge3-latest-Linux-x86_64.sh)"
      - rm -f Downloads/Miniforge3-latest-Linux-x86_64.sh
      - rm -f "$$(readlink -f Downloads/Jmol-latest-binary.zip)"
      - rm -f Downloads/Jmol-latest-binary.zip
      - rm -f "$$(readlink -f Downloads/iso-latest.zip)"
      - rm -f Downloads/iso-latest.zip
      - *download_script

  install:
    #service: setup-nonet
    # There is a chicken-or-egg problem with the installation of miniforge/conda needed to download everything needed for the install
    # reinstall will simply reinstall miniforge/conda even though it is installed also as part of download
    service: setup-nonet
    type: setup
    script: &install_script
      - echo "INSTALL";
      - mkdir -p ~/.local/share
      - |
        if [ ! -e ~/.local/share/miniforge ]; then
          echo "Install miniforge (needed to complete downloads)"
          bash ~/Downloads/Miniforge3-latest-Linux-x86_64.sh -b -s -p ~/.local/share/miniforge
          source ~/.local/share/miniforge/etc/profile.d/conda.sh
          conda config --add envs_dirs "$$DEVDIR/conda/envs"
          conda config --add pkgs_dirs "$$DEVDIR/conda/pkgs"
          conda config --set auto_activate_base false
        else
          source ~/.local/share/miniforge/etc/profile.d/conda.sh
        fi
      - conda list --name py27 > /dev/null || { echo "Files for Python 2.7 missing, please re-run download" && exit 1; }
      - conda list --name py39 > /dev/null || { echo "Files for Python 3.9 missing, please re-run download" && exit 1; }
      - (conda activate py39 && python -m venv httk-venvs/py39 && source httk-venvs/py39/bin/activate && python -m pip install --find-links=httk-venvs/wheelhouse -r httk/requirements.txt)
      - (conda activate py27 && virtualenv httk-venvs/py27 && source httk-venvs/py27/bin/activate && python -m pip install --find-links=httk-venvs/wheelhouse -r httk/requirements.txt)
      - |
        if [ ! -e ~/.local/share/jmol ]; then
          mkdir ~/.local/share/jmol
          cd ~/.local/share/jmol
          unzip ~/Downloads/Jmol-latest-binary.zip
          LATEST=$$(ls -t | head -1)
          ln -sf "$$LATEST" latest
          chmod +x latest/jmol.sh
        fi
      - |
        if [ ! -e ~/.local/share/isotropy ]; then
          mkdir ~/.local/share/isotropy
          cd ~/.local/share/isotropy
          unzip ~/Downloads/iso-latest.zip
        fi

  reinstall:
    #service: setup-nonet
    service: setup
    type: setup
    script: &reinstall_script
      - echo "REINSTALL"
      - rm -rf ~/.local/share/miniforge
      - rm -rf ~/.local/share/jmol
      - rm -rf ~/.local/share/isotropy
      - rm -rf httk-venvs
      - python3 -m venv httk-venvs/py27
      - python3 -m venv httk-venvs/py39
      - *install_script

  update-check:
    service: setup
    type: setup
    script: &update_check_script
      - echo "UPDATE CHECK"
      - echo "Development environment: update manually with git pull"
      - exit 0

  update:
    service: setup
    type: setup
    script:
      - echo "UPDATE"
      - echo "Development environment: update manually with git pull"

  httk-console:
    service: run
    type: console
    script:
      - echo "httk-devel"
      - export PATH=$$PATH:~/.local/share/jmol/latest:~/.local/share/isotropy
      - export ISODATA=~/.local/share/isotropy/
      - source ~/.local/share/miniforge/etc/profile.d/conda.sh
      - cd httk
      - source init.shell
      - bash

    desktop:

      file: |
        [Desktop Entry]
        Name=httk console (container)
        Comment=httk console
        Exec=httk-console %U
        Terminal=true
        Type=Application
        Icon=httk
        Categories=Development;

      icons:
        - source: .local/share/icons/hicolor/scalable/httk.svg
          size: scalable
          dest: httk.svg

services:

  ## COMMON PART ##

  common: &common

    image: "cdc-u24"

    entrypoint: ["/bin/tini", "/bin/bash", "--", "-c", "$$(printf \"%s\\n\" \"$@\"); sleep infinity"]
    network_mode: none

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
      XDG_CURRENT_DESKTOP: "GNOME"
      BROWSER: "falkon"

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    devices:
      - "/dev/dri:/dev/dri"

    security_opt:
      - no-new-privileges

    userns_mode: "keep-id"


  setup:
    <<: *common

    network_mode: bridge

  setup-nonet:
    <<: *common

    network_mode: none

  run:
    <<: *common

    network_mode: bridge

    volumes:
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    x-features:
      - x11
