version: "3.8"

x-application:

  readme: |
    Microsoft365: run the progressive web apps for MS Teams and OneDrive (which includes Word, Excel, etc.)

  override-default: |
    version: "3.8"

  env-default: |
    # This container has no configurable options

  global-launcher:
    name: microsoft365
    default-action: tray
    tray:
      icon: microsoft365
      entries:
        - name: "Teams"
          wmclass-file: install/microsoft365/msteams.wmclass
          launch: msteams
        - name: "OneDrive"
          wmclass-file: install/microsoft365/onedrive.wmclass
          launch: onedrive
        - name: "Outlook"
          wmclass-file: install/microsoft365/outlook.wmclass
          launch: outlook
        - name: "Forms"
          wmclass-file: install/microsoft365/msforms.wmclass
          launch: msforms
    desktop:
      file: |
        [Desktop Entry]
        Name=Microsoft 365 tray (container)
        Comment=Tray app for Microsoft 365 PWA tools
        GenericName=Office utils
        Exec=microsoft365 tray
        Icon=microsoft365
        Type=Application
        Categories=Network;
        Path=/usr/bin

      icons:
        - source: outlook.png
          dest: microsoft365.png

services:

  ## COMMON PART ##

  common: &common

    image: "cdc-u24"

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "/tmp/${USER}/run"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"

    cap_drop:
      - ALL

    cap_add:
      - SYS_CHROOT

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes:
      - "${CDC_APP_DIR}/home:/home/${USER}:rw"

    devices:
      - "/dev/dri:/dev/dri"

    userns_mode: "keep-id"

    network_mode: none

  ## INSTALL ##

  download: &download
    <<: *common

    network_mode: bridge

    x-app-features:
      - x11

    command:
      - echo "DOWNLOAD"
      - mkdir -p ~/install/microsoft365
      - echo "***********************************************************"
      - echo "Running chrome, please navigate to the microsoft 365 apps"
      - echo "and use the 'install' icon in the navigator field for:"
      - echo "- OneDrive"
      - echo "- Teams"
      - echo "- Outlook"
      - echo "- Forms"
      - echo "The easiest way to trigger the install icon is to"
      - echo "go via the '9-dots-menu' to these applications."
      - echo "***********************************************************"
      - google-chrome ${OZONE_FLAG} 'https://www.microsoft365.com/'

  install: &install
    <<: *common

    command:
      - echo "INSTALL"
      - for APPNAME in "Microsoft Teams|msteams" "Microsoft OneDrive|onedrive" "Outlook (PWA)|outlook" "Microsoft Forms|msforms"; do
          APP_FULL_NAME=$${APPNAME%|*};
          DESKTOP_FILE="$$(find ~/.local/share/applications/ -name "*.desktop" | xargs grep -l "^Name=$${APP_FULL_NAME}$$")";
          if [ -n "$$DESKTOP_FILE" ]; then
            DESKTOP_FILE_NAME=$$(basename $$DESKTOP_FILE .desktop);
            COMMAND=$$(awk -FExec= '/^Exec=/{print $2; exit}' "$$DESKTOP_FILE");
            CHROMIUM_APP_ID="$${DESKTOP_FILE_NAME%*-Default}";
            CHROMIUM_APP_ID="$${CHROMIUM_APP_ID##chrome-}";
            echo "Chromium app ID for $$APP_FULL_NAME is $$CHROMIUM_APP_ID";
            echo -e "#!/bin/bash\nexec $${COMMAND} \"\$$@\" \n" > ~/install/microsoft365/$${APPNAME#*|}.sh;
            chmod +x ~/install/microsoft365/$${APPNAME#*|}.sh;
            echo -n "$$CHROMIUM_APP_ID" > ~/install/microsoft365/$${APPNAME#*|}.appid;
            echo -n "crx_$$CHROMIUM_APP_ID" > ~/install/microsoft365/$${APPNAME#*|}.wmclass;
            cp ~/.local/share/icons/hicolor/256x256/apps/"chrome-$${CHROMIUM_APP_ID}-Default.png" ~/.local/share/icons/hicolor/256x256/apps/$${APPNAME#*|}.png;
          else
            echo "Warning, $${APPNAME_FULL_NAME} does not seem to be downloaded and will thus not be installed, re-run the download step and retry.";
          fi;
        done

  ## UPDATE ##

  update-check: &update-check
    <<: *common

    command:
      - echo "UPDATE CHECK"
      - echo "Progressive web app: updates are automatic" "$$@"
      - exit 0

  update: &update
    <<: *install


  ## EXECUTE ###

  msteams:
    <<: *common

    x-app-container_name: cdc_microsoft365
    x-app-features:
      - video
      - sound
      - x11

    network_mode: bridge

    command:
      - echo "MSTEAMS"
      - if [ ! -e install/microsoft365/msteams.sh ]; then
          echo "MS Teams is not installed, please re-run installation.";
          exit 0;
        fi
      - pipewire-pulse &
      - echo "== LAUNCHER:"
      - cat install/microsoft365/msteams.sh
      - echo EXECUTING install/microsoft365/msteams.sh ${OZONE_FLAG} "$$@"
      - exec install/microsoft365/msteams.sh ${OZONE_FLAG} "$$@"

    x-launcher:

      desktop:
        file: |
          [Desktop Entry]
          Name=Microsoft Teams (container)
          Comment=Microsoft Teams
          GenericName=Internet Messenger
          StartupWMClass=msteams
          Exec=msteams
          Icon=msteams
          Type=Application
          Categories=Network;InstantMessaging;
          Path=/usr/bin

        wmclass-file: install/microsoft365/msteams.wmclass

        icons:
          - source: msteams.png
            dest: msteams.png

  onedrive:
    <<: *common

    x-app-container_name: cdc_microsoft365
    x-app-features:
      - x11
      
    network_mode: bridge

    command:
      - echo "ONEDRIVE"
      - if [ ! -e install/microsoft365/onedrive.sh ]; then
          echo "OneDrive is not installed, please re-run installation.";
          exit 0;
        fi
      - exec install/microsoft365/onedrive.sh ${OZONE_FLAG} "$$@"

    x-launcher:

      desktop:
        file: |
          [Desktop Entry]
          Name=Microsoft OneDrive (container)
          StartupWMClass=onedrive
          Comment=Microsoft OneDrive
          GenericName=Cloud file tool
          Exec=onedrive
          Icon=onedrive
          Type=Application
          Categories=Network;
          Path=/usr/bin

        wmclass-file: install/microsoft365/onedrive.wmclass

        icons:
          - source: onedrive.png
            dest: onedrive.png

  outlook:
    <<: *common

    x-app-container_name: cdc_microsoft365
    x-app-features:
      - x11
      
    network_mode: bridge

    command:
      - echo "OUTLOOK"
      - if [ ! -e install/microsoft365/outlook.sh ]; then
          echo "Outlook is not installed, please re-run installation.";
          exit 0;
        fi
      - exec install/microsoft365/outlook.sh ${OZONE_FLAG} "$$@"

    x-launcher:

      desktop:
        file: |
          [Desktop Entry]
          Name=Outlook (PWA) (container)
          Comment=Microsoft Outlook
          GenericName=Email and calendar
          StartupWMClass=outlook
          Exec=outlook
          Icon=outlook
          Type=Application
          Categories=Office;
          Path=/usr/bin
          MimeType=x-scheme-handler/mailto;
          Actions=New-event;New-message;Open-calendar

          [Desktop Action New-event]
          Name=New event
          Exec=outlook --app-launch-url-for-shortcuts-menu-item=https://outlook.office.com/calendar/deeplink/compose

          [Desktop Action New-message]
          Name=New message
          Exec=outlook --app-launch-url-for-shortcuts-menu-item=https://outlook.office.com/mail/deeplink/compose

          [Desktop Action Open-calendar]
          Name=Open calendar
          Exec=outlook --app-launch-url-for-shortcuts-menu-item=https://outlook.office.com/calendar

        wmclass-file: install/microsoft365/outlook.wmclass

        icons:
          - source: outlook.png
            dest: outlook.png

  msforms:
    <<: *common

    x-app-container_name: cdc_microsoft365
    x-app-features:
      - x11

    network_mode: bridge

    command:
      - echo "MSFORMS"
      - if [ ! -e install/microsoft365/msforms.sh ]; then
          echo "Forms is not installed, please re-run installation.";
          exit 0;
        fi
      - exec install/microsoft365/msforms.sh ${OZONE_FLAG} "$$@"

    x-launcher:

      desktop:
        file: |
          [Desktop Entry]
          Name=Microsoft Forms (container)
          Comment=Tool to create online surveys, forms, polls and quizzies
          GenericName=Form tool
          StartupWMClass=msforms
          Exec=msforms
          Icon=msforms
          Type=Application
          Categories=Network;
          Path=/usr/bin

        wmclass-file: install/microsoft365/msforms.wmclass

        icons:
          - source: msforms.png
            dest: msforms.png


  ## INTERACTIVE ##

  interactive:
    <<: *common

    x-app-container_name: cdc_microsoft365
    x-app-features:
      - video
      - sound
      - x11

    command:
      - echo "INTERACTIVE"
      - bash "$$@"
