version: "3.8"

# Note: google chrome is installed in the image itself as it is needed for progressive web apps.
# Hence, this app file is just wrapping running the container-installed google-crome.

x-application:

  readme: |
    Google Chrome: web browser developed by Google.

  override-default: |
    version: "3.8"

    services:
      google-chrome:
         volumes:
           - "${HOME}/Documents/containers/browser:/home/${USER}/Documents/containers/browser"
         working_dir: "/home/${USER}/Documents/containers/browser"

  env-default: |
    # This container has no configurable options

x-launchers:

  download:
    service: setup
    type: setup

    # Zoom doesn't keep track of versions via filenames. TODO: implement handling of this so old versions are kept.
    script: &download_script
      - echo "DOWNLOAD"
      - echo "(Nothing to download, google-chrome is part of the system image.)"

  redownload:
    service: setup
    type: setup
    script: &redownload_script
      - *download_script

  install:
    service: setup-nonet
    type: setup
    script: &install_script
      - echo "INSTALL";
      - mkdir -p ~/.local/share/icons/hicolor/16x16/apps ~/.local/share/icons/hicolor/24x24/apps ~/.local/share/icons/hicolor/32x32/apps ~/.local/share/icons/hicolor/48x48/apps ~/.local/share/icons/hicolor/64x64/apps ~/.local/share/icons/hicolor/128x128/apps ~/.local/share/icons/hicolor/256x256/apps
      - cp /usr/share/icons/hicolor/16x16/apps/google-chrome.png ~/.local/share/icons/hicolor/16x16/apps/.
      - cp /usr/share/icons/hicolor/24x24/apps/google-chrome.png ~/.local/share/icons/hicolor/24x24/apps/.
      - cp /usr/share/icons/hicolor/32x32/apps/google-chrome.png ~/.local/share/icons/hicolor/32x32/apps/.
      - cp /usr/share/icons/hicolor/48x48/apps/google-chrome.png ~/.local/share/icons/hicolor/48x48/apps/.
      - cp /usr/share/icons/hicolor/64x64/apps/google-chrome.png ~/.local/share/icons/hicolor/64x64/apps/.
      - cp /usr/share/icons/hicolor/128x128/apps/google-chrome.png ~/.local/share/icons/hicolor/128x128/apps/.
      - cp /usr/share/icons/hicolor/256x256/apps/google-chrome.png ~/.local/share/icons/hicolor/256x256/apps/.

  reinstall:
    service: setup-nonet
    type: setup
    script: &reinstall_script
      - *install_script

  update-check:
    service: setup
    type: setup
    script: &update_check_script
      - echo "UPDATE CHECK"
      - echo "Part of system image; updates that way"
      - exit 0

  update:
    service: setup
    type: setup
    prelaunchers:
      - redownload
      - reinstall
    script:
      - echo "UPDATE"

  google-chrome:
    service: run
    type: background

    script:
      - echo "GOOGLE_CHROME"
      - pipewire-pulse &
      - exec google-chrome $${CDC_OZONE_FLAGS} "$$@"

    desktop:
      file: |
        [Desktop Entry]
        Name=Google Chrome (container)
        Comment=Access the Internet
        Exec=google-chrome %U
        StartupNotify=true
        StartupWMClass=google-chrome
        Terminal=false
        Icon=google-chrome
        Type=Application
        Categories=Network;WebBrowser;
        MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;
        Actions=new-window;new-private-window;

        [Desktop Action new-window]
        Name=New Window
        Exec=/usr/bin/google-chrome

        [Desktop Action new-private-window]
        Name=New Incognito Window
        Exec=/usr/bin/google-chrome --incognito

      icons:
        - source: google-chrome.png
          dest: google-chrome.png

  interactive:
    service: run
    console: true
    script:
      - echo "INTERACTIVE"
      - bash "$$@"

services:

  common: &common

    image: "cdc-u24"
    entrypoint: ["/bin/tini", "/bin/bash", "--", "-c", "$$(printf \"%s\\n\" \"$@\"); sleep infinity"]

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "/tmp/${USER}/run"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"
      DESKTOP_SESSION: "${DESKTOP_SESSION}"

    cap_drop:
      - ALL

    cap_add:
      - SYS_CHROOT

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes:
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    userns_mode: "keep-id"

    network_mode: none

    devices:
      - "/dev/dri:/dev/dri"

  setup:
    <<: *common

    network_mode: bridge

  setup-nonet:
    <<: *common

    network_mode: none

  run:
    <<: *common

    network_mode: bridge

    x-features:
      - video
      - sound
      - wayland-fallback-x11
