version: "3.8"

x-application:

  readme: |
    Zoom: videotelephony software program.

    This container uses the x11 server on your desktop (i.e., likely xwayland if you are
    running Wayland), which is not great from a security barrier perspective. Zoom has support
    to run directly under wayland, but in present versions this support seem to cause issues
    (crashes, incomplete user interface, etc.), which is probably why current versions of Zoom
    at the time of writing this defaults to x11 even if Wayland is available.

    Use together with legacy-screenshare-helper (https://github.com/httk/legacy-screenshare-helper)
    to support screensharing.

  override-default: |
    version: "3.8"

    # Comment out as desired below to give zoom access to dbus session and/or system bus
    #
    #services:
    #  zoom:
    #    volumes:
    #      - "${CDC_DBUS_PATH}:/tmp/${USER}/run/bus:rw"
    #      - "${CDC_DBUS_SYSTEM_BUS_PATH}:/run/dbus/system_bus_socket:rw"
    #    environment:
    #      DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/${USER}/run/bus"
    #      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"
    #    x-launcher:
    #      dbus-proxy: --filter
    #      dbus-system-proxy: --filter
    #

  env-default: |
    # No configurable options


services:

  ## COMMON PART ##

  common: &common

    image: "desktop-container-default"

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
      XDG_CURRENT_DESKTOP: "GNOME"
      BROWSER: "falkon"
      TERM: "xterm"
      XTERM_LOCALE: "en_US.UTF-8"
      XTERM_SHELL: "/usr/bin/bash"
      DISPLAY: "${DISPLAY}"
      XAUTHORITY: "${XAUTHORITY}"

    cap_drop:
      - ALL
    cap_add:
      - SYS_CHROOT

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "512m"

    volumes: &common-volumes
      - "${CDC_APP_DIR}/home:/home/${USER}:rw"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY}:${XAUTHORITY}:rw"
      - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"

    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/snd:/dev/snd"

    security_opt:
      - "label=disable"

    userns_mode: "keep-id"


  ## INSTALL ##

  download: &download
    <<: *common

    # Note: the deb archive is needed just to get the icon, which does not seem to be included in the standalone install (?)
    # Zoom doesn't keep track of versions via filenames. TODO: implement handling of this so old versions are kept.
    command:
      - echo "DOWNLOAD"
      - mkdir -p Downloads
      - curl -L -o Downloads/zoom_x86_64.tar.xz "https://zoom.us/client/latest/zoom_x86_64.tar.xz"
      - curl -L -o Downloads/zoom_amd64.deb "https://zoom.us/client/latest/zoom_amd64.deb"

  install: &install
    <<: *common

    command:
      - VERSION="$${1:-zoom_x86_64.tar.xz}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/zoom &&
        mkdir ~/zoom &&
        cd ~/zoom &&
        mkdir tmp &&
        cd tmp &&
        ar x ~/Downloads/zoom_amd64.deb &&
        tar -xf data.tar.xz &&
        cp ./usr/share/pixmaps/Zoom.png ../. &&
        cd .. && rm -rf tmp &&
        tar -xf ~/Downloads/"$$VERSION" &&
        mkdir -p ~/.local/share/applications &&
        echo -e "[Desktop Entry]\nName=ZoomLauncher\nComment=Zoom Video Conference\nExec=/home/${USER}/zoom/zoom/ZoomLauncher %U\nTerminal=false\nType=Application\nCategories=Network;\nMimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;\nX-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall\nName[en_US]=ZoomLauncher" > ~/.local/share/applications/ZoomLauncher.desktop &&
        update-desktop-database ~/.local/share/applications/

  ## UPDATE ##

  update-check: &update-check
    <<: *common

    command:
      - echo "UPDATE CHECK"
      - mkdir -p Downloads
      - if [ -e Downloads/zoom_x86_64.tar.xz ]; then
          LASTMOD_LINE="$$(curl -sI -L "https://zoom.us/client/latest/zoom_x86_64.tar.xz" | grep -i '^last-modified:' | cut "-d:" -f2- | sed 's/^\s*\|\s$$//g')";
          if [ -z "$$LASTMOD_LINE" ]; then
            echo "Could not get last modified date";
            exit 0;
          fi;
          REMOTE_TS="$$(date -d "${LASTMOD_LINE}" +%s)";
          LOCAL_TS="$$(date -r "Downloads/zoom_x86_64.tar.xz" +%s)";
          if [ "$$REMOTE_TS" -lt "$$LOCAL_TS" ]; then
            echo "No new version";
            exit 0;
          fi;
        fi;
      - echo "File missing, or server-side file newer"
      - exit 1

  update: &update
    <<: *install


  ## EXECUTE ###

  zoom:
    <<: *common

    container_name: cdc_zoom_zoom

    command:
      - echo "ZOOM"
      - cd zoom/zoom
      - pipewire-pulse &
      - LD_LIBRARY_PATH=/home/rar/zoom/zoom:/home/rar/zoom/zoom/Qt/lib exec ./zoom "$$@"

    x-launcher:

      # zoom in x11 mode does not need dbus?
      #dbus-proxy: ""

      devices:
        - video

      desktop:

        file: |
          [Desktop Entry]
          Name=Zoom (container)
          StartupWMClass=zoom
          Comment=Zoom Video Conference
          Exec=zoom %U
          Terminal=false
          Type=Application
          Icon=zoom
          Categories=Network
          MimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;
          X-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall

        icons:
          - source: zoom/Zoom.png
            size: 256
            dest: zoom.png


  ## INTERACTIVE ##

  interactive:
    <<: *common

    command:
      - echo "INTERACTIVE"
      - bash
