version: "3.8"

x-application:

  readme: |
   codex console development environment

  override-default: |
    version: "3.8"

    services:
      run:
         volumes:
           - "${HOME}/Documents/containers/devel/codex:/home/${USER}/Documents/containers/devel/codex"
         working_dir: "/home/${USER}/Documents/containers/devel/codex"

      setup:
         volumes:
           - "${HOME}/Documents/containers/devel/codex:/home/${USER}/Documents/containers/devel/codex"
         working_dir: "/home/${USER}/Documents/containers/devel/codex"

      setup-nonet:
         volumes:
           - "${HOME}/Documents/containers/devel/codex:/home/${USER}/Documents/containers/devel/codex"
         working_dir: "/home/${USER}/Documents/containers/devel/codex"


  env-default: |
    # This container has no configurable options

  images:
    u24:
      pkgs:
        - python3
        - python3-venv
        - python3-pip
        - pipx
        - npm


x-launchers:
  download:
    service: setup
    type: setup

    script: &download_script
      - echo "DOWNLOAD"
      - export PATH="/home/${USER}/.local/bin:$${PATH}"
      - export DEV_DIR="$$(pwd -P)"
      - mkdir -p ~/.local/share/icons/hicolor/scalable
      - curl -L -o ~/.local/share/icons/hicolor/scalable/python-console.svg https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/files/python-logo-only.svg
      - mkdir -p "uv/cache" "uv/home"
      - rm -rf ~/.local/share/uv
      - ln -s "$$(pwd -P)/uv/home" ~/.local/share/uv
      - export UV_CACHE_DIR="$$(pwd -P)/uv/cache"
      - pipx install --force uv
      - mkdir -p ~/Downloads

  redownload:
    service: setup
    type: setup
    script: &redownload_script
      - echo "REDOWNLOAD"
      - *download_script

  install:
    service: setup-nonet
    type: setup
    script: &install_script
      - echo "INSTALL";
      - export DEV_DIR="$$(pwd -P)"
      - export PATH="/home/${USER}/.local/bin:$${PATH}"
      - export UV_CACHE_DIR="$$(pwd -P)/uv/cache"
      - mkdir -p ~/.local/share/npm/global
      - npm config set prefix ~/.local/share/npm/global
      - npm i -g @openai/codex@latest

  reinstall:
    #service: setup-nonet
    service: setup
    type: setup
    script: &reinstall_script
      - echo "REINSTALL"
      - *install_script

  update-check:
    service: setup
    type: setup
    script: &update_check_script
      - echo "UPDATE CHECK"
      - echo "Development environment, nothing to auto-update"
      - exit 0

  update:
    service: setup
    type: setup
    script:
      - echo "UPDATE"
      - npm i -g @openai/codex@latest

  codex-console:
    service: run
    type: console
    script:
      - echo "python-console"
      - export DEV_DIR="$$(pwd -P)"
      - export PATH=~/.local/bin:~/.local/share/npm/global/bin:"$$PATH"
      - export UV_CACHE_DIR="$$(pwd -P)/uv/cache"
      - export CONDA_PKGS_DIRS="$$(pwd -P)/conda/pkgs"
      - export CONDA_ENVS_PATH="$$(pwd -P)/httk/.venvs/conda"
      - echo "===================================================================================================="
      - echo ""
      - echo "You have started the codex console version"
      - echo ""
      - echo "  You have access to python3 with venv, pip, and uv to set up venvs"
      - echo "  To run codex, just issue:"
      - echo "    codex"
      - echo ""
      - echo "===================================================================================================="
      - bash

    desktop:

      file: |
        [Desktop Entry]
        Name=codex console (container)
        Comment=codex console
        Exec=codex-console %U
        Terminal=true
        Type=Application
        Icon=python-console
        Categories=Development;

      icons:
        - source: .local/share/icons/hicolor/scalable/python-console.svg
          size: scalable
          dest: codex-console.svg

services:

  ## COMMON PART ##

  common: &common

    image: "cdc-u24"

    entrypoint: ["/cdc/entrypoint"]
    network_mode: none

    working_dir: /home/$USER
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
      XDG_CURRENT_DESKTOP: "${XDG_CURRENT_DESKTOP}"
      NO_AT_BRIDGE: 1

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    devices:
      - "/dev/dri:/dev/dri"

    security_opt:
      - no-new-privileges

    userns_mode: "keep-id"


  setup:
    <<: *common

    network_mode: bridge

  setup-nonet:
    <<: *common

    network_mode: none

  run:
    <<: *common

    network_mode: bridge

    volumes:
      - "${CDC_APP_PATH}/home:/home/${USER}:rw"

    x-features:
      - x11
