#!/usr/bin/bash

set -e

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

if [ "$1" == "-h" ]; then
    echo "Usage: $0 [<app dir>]"
    exit 0
fi

DEST="$1"
if [ "$DEST" != "" ]; then
    cd "$DEST"
fi
APP="$(basename -- "$(pwd -P)")"
DEST_ABSPATH="$(pwd -P)"

PODMAN_CONFIG="$(podman-compose -f compose.yaml -f override.yaml config)"

function POST_PROCESS_LAUNCHER() {
    CDCLAUNCHER=$1
    LAUNCHER=$2
    YQPATH=$3

    ln -sf "$CDCLAUNCHER" "$LAUNCHER"
    if [ "$(echo "$PODMAN_CONFIG" | yq "${YQPATH}.desktop")" != "null" ]; then
	mkdir -p ~/.local/share/applications
	echo "$PODMAN_CONFIG" | yq -r "${YQPATH}.desktop.file" > ~/.local/share/applications/"${LAUNCHER}_cdc.desktop"
	sed -i "s|^Exec=$LAUNCHER|Exec=\"${DEST_ABSPATH}/$LAUNCHER\"|" ~/.local/share/applications/"${LAUNCHER}_cdc.desktop"
	WMCLASS_FILE="$(echo "$PODMAN_CONFIG" | yq -r "${YQPATH}.desktop.\"wmclass-file\"")"
	if [ -n "$WMCLASS_FILE" -a "$WMCLASS_FILE" != "null" ]; then
	    WMCLASS=$(cat "home/$WMCLASS_FILE")
	    sed -i "s|^StartupWMClass=.*\$|StartupWMClass=$WMCLASS|" ~/.local/share/applications/"${LAUNCHER}_cdc.desktop"
	fi
	desktop-file-validate ~/.local/share/applications/"${LAUNCHER}_cdc.desktop"
	echo "Wrote: ~/.local/share/applications/${LAUNCHER}_cdc.desktop"

	ICONS_NBR=$(echo "$PODMAN_CONFIG" | yq -r "${YQPATH}.desktop.icons | length")
	for (( ICON_IDX=0; ICON_IDX<ICONS_NBR; ICON_IDX++ )); do
	    # Sanetize icon paths somewhat
	    ICON_SRC=$(echo "$PODMAN_CONFIG" | yq -r "${YQPATH}.desktop.icons[$ICON_IDX].source")
	    ICON_SRC=${ICON_SRC//[^[:ascii:]]}
	    ICON_SRC=${ICON_SRC//../}
	    ICON_DEST=$(echo "$PODMAN_CONFIG" | yq -r "${YQPATH}.desktop.icons[$ICON_IDX].dest")
	    ICON_DEST=${ICON_DEST//[^[:ascii:]]}
	    ICON_DEST=${ICON_DEST//../}
	    ICON_PLACE=$(echo "$PODMAN_CONFIG" | yq -r "${YQPATH}.desktop.icons[$ICON_IDX].dest")
	    if [ "${ICON_DEST}" == "${ICON_DEST#$APP/}" ]; then
		for ICON_SIZE in "scalable" "512x512" "256x256" "192x192" "128x128" "96x96" "72x72" "64x64" "48x48" "36x36" "32x32" "24x24" "22x22" "16x16" "8x8"; do
		    ICON_SRC_PATH="home/.local/share/icons/hicolor/$ICON_SIZE/apps/${ICON_SRC}"
		    ICON_DST_PATH=~/.local/share/icons/hicolor/"${ICON_SIZE}/apps"
		    if [ -e "$ICON_SRC_PATH" ]; then
			echo "Writing: $ICON_DST_PATH"
			mkdir -p "$ICON_DST_PATH"
			cp "$ICON_SRC_PATH" "$ICON_DST_PATH"
		    fi
		done
	    else
		ICON_DEST_PATH="${ICON_DEST#$APP/}"
		ICON_DEST_DIR=$(dirname "$ICON_DEST_PATH")
		ICON_SRC_PATH="home/${ICON_SRC}"
		mkdir -p ~/.local/share/"$APP/${ICON_DEST_DIR}"
		echo "Writing: ~/.local/share/${APP}/${ICON_DEST_PATH}"
		cp "home/${ICON_SRC_PATH}" ~/.local/share/"${APP}/${ICON_DEST_PATH}"
	    fi
	done
    fi
}

for LAUNCHER in $(echo "$PODMAN_CONFIG" | yq -r '.services | keys[]'); do
    if [ "$(echo "$PODMAN_CONFIG" | yq -r ".services.\"$LAUNCHER\".\"x-application\"")" != "null" ]; then
	POST_PROCESS_LAUNCHER "$SCRIPTPATH/cdc-launch" "$LAUNCHER" ".services.\"$LAUNCHER\".\"x-application\""
    fi
done

if [ "$(echo "$PODMAN_CONFIG" | yq -r '."x-application"."global-launcher"')" != "null" ]; then
    LAUNCHER="$(echo "$PODMAN_CONFIG" | yq -r '."x-application"."global-launcher".name')"
    POST_PROCESS_LAUNCHER "$SCRIPTPATH/cdc-launch-global" "$LAUNCHER" '."x-application"."global-launcher"'
fi

update-desktop-database ~/.local/share/applications/
gtk-update-icon-cache -f -t ~/.local/share/icons/hicolor
