#!/bin/bash

set -e

SCRIPTPATH="$(dirname -- "$(realpath -- "$0")")"
DEST_ABSPATH="$(cd -- "$DEST"; pwd -P)"
PODMAN_CONFIG=$(podman-compose -f compose.yaml config 2>/dev/null)

if [ "$(echo "$PODMAN_CONFIG" | yq -r '.services."install-clean"')" != "null" ]; then
    "$SCRIPTPATH/cdc-launch" "install-clean" "$1"
fi
if [ "$(echo "$PODMAN_CONFIG" | yq -r '.services."install-clean"')" != "null" ]; then
    "$SCRIPTPATH/cdc-launch" install "$1"
fi
