version: "3.8"

x-application:

  readme: |
    Blender: 3D computer graphics software tool.

  override-default: |
    version: "3.8"

  env-default: |
    # This container has no configurable options

services:

  ## COMMON PART ##

  common: &common

    image: "desktop-container-default"

    working_dir: /home/${USER}
    user: "${USER}"

    environment: &common-env
      LANG: "${LANG}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
      XDG_CURRENT_DESKTOP: "GNOME"
      BROWSER: "falkon"
      WAYLAND_DISPLAY: "${WAYLAND_DISPLAY}"

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges

    read_only: true
    tmpfs:
      - /tmp
      - /run

    shm_size: "1G"

    volumes: &common-volumes
      - "${CDC_APP_DIR}/home:/home/${USER}:rw"
      - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"
      - "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${USER}/run/${WAYLAND_DISPLAY}:ro"

    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/snd:/dev/snd"

    security_opt:
      - "label=no-new-privileges"

    userns_mode: "keep-id"


  ## INSTALL ##

  download: &download
    <<: *common

    command:
      - echo "DOWNLOAD"
      - mkdir -p Downloads
      - THANKSURL="$$(curl -L 'https://www.blender.org/download/' | cat | sed -n '\|^.*"\(https://www.blender.org/download/release/Blender[0-9.]\+/blender-[0-9.]\+-linux-x64.tar.xz[^\"]*\)".*$$|{s||\1|p;q}')"
      - LATESTURL="$$(curl -L "$$THANKSURL" | cat | sed -n '\|^.*"\(https:.*/Blender[0-9.]\+/blender-[0-9.]\+-linux-x64.tar.xz\)".*$$|{s||\1|p;q}')"
      - LATESTFILENAME="$${LATESTURL##*/}"
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
        fi;
      - curl -L -o Downloads/$$LATESTFILENAME "$$LATESTURL" && ln -sf $$LATESTFILENAME Downloads/blender-latest-linux-x64.tar.xz

  install: &install
    <<: *common

    command:
      - VERSION="$${1:-blender-latest-linux-x64.tar.xz}";
      - echo "INSTALL $$VERSION";
      - rm -rf ~/install &&
        mkdir ~/install &&
        cd ~/install &&
        tar -xf ~/Downloads/blender-latest-linux-x64.tar.xz &&
        mv blender-* blender &&
        mkdir -p ~/.local/share/applications &&
        cp blender/blender.desktop ~/.local/share/applications/blender.desktop &&
        sed -i 's%^Exec=.*$$%Exec=/home/$${USER}/install/blender/blender%'  ~/.local/share/applications/blender.desktop

  ## UPDATE ##

  update-check: &update-check
    <<: *common

    command:
      - echo "UPDATE CHECK"
      - THANKSURL="$$(curl -L -N 'https://www.blender.org/download/' | cat | sed -n '\|^.*"\(https://www.blender.org/download/release/Blender[0-9.]\+/blender-[0-9.]\+-linux-x64.tar.xz[^\"]*\)".*$$|{s||\1|p;q}')"
      - LATESTURL="$$(curl -L -N "$$THANKSURL" | sed -n '\|^.*"\(https:.*/Blender[0-9.]\+/blender-[0-9.]\+-linux-x64.tar.xz\)".*$$|{s||\1|p;q}')"
      - LATESTFILENAME="$${LATESTURL##*/}";
      - if [ -z "$$LATESTFILENAME" ]; then
          echo "Failed to determine latest version.";
          exit 1;
      - fi
      - mkdir -p Downloads
      - if [ -e "Downloads/$$LATESTFILENAME" ]; then
          echo "No new version";
          exit 0;
        fi
      - echo "File missing, or server-side file newer"
      - exit 1

  update: &update
    <<: *install


  ## EXECUTE ###

  blender:
    <<: *common

    container_name: cdc_blender_blender

    command:
      - echo "BLENDER"
      - cd install/blender
      - pipewire-pulse &
      - exec ./blender "$$@"

    x-launcher:
      desktop:
        file: |
          [Desktop Entry]
          Name=Blender (container)
          StartupWMClass=Blender
          PrefersNonDefaultGPU=true
          GenericName=3D modeler
          Comment=3D modeling, animation, rendering and post-production
          Exec=blender %f
          Terminal=false
          Type=Application
          Icon=blender
          Categories=Graphics;3DGraphics;
          MimeType=application/x-blender;
          Keywords=3d;cg;modeling;animation;painting;sculpting;texturing;video editing;video tracking;rendering;render engine;cycles;python;

        icons:
          - source: install/blender/blender.svg
            size: scalable
            dest: blender.svg

  ## INTERACTIVE ##

  interactive:
    <<: *common

    command:
      - echo "INTERACTIVE"
      - bash "$$@"
